name: Build and Deploy Application

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

env:
  ResourceGroup: ent-demo-rg-3
  SwaName: ent-demo-swa-3

jobs:
  build-and-test:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true


      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
          include-prerelease: false

      - name: 'Run Tests'
        run: dotnet test --configuration Release **/*Tests.csproj   

          
      - name: Client Build
        run: dotnet publish ./Client/Client.csproj --output ./dist-client

      - name: Api Build
        run: dotnet publish ./Api/Api.csproj --output ./dist-api

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Get SWA deployment token
        id: get-secret-from-cli
        uses: azure/CLI@v1
        with:
          azcliversion: 2.42.0
          inlineScript: |
            SWA_SECRETS=$(az staticwebapp secrets list -n $SwaName -g $ResourceGroup --query 'properties.apiKey' -o tsv )
            echo "::add-mask::$SWA_SECRETS"
            echo SWA_SECRETS=$SWA_SECRETS >> $GITHUB_OUTPUT

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - name: Deploy Artifacts to SWA
        run: |
          npm install -g @azure/static-web-apps-cli
          swa deploy -a dist-client/wwwroot -i dist-api --deployment-token ${{ steps.get-secret-from-cli.outputs.SWA_SECRETS }} --env production

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_OCEAN_086E6E803 }}
          action: "close"
