name: Create and Setup SWA Infrastructure

on:
  workflow_dispatch

env:
ResourceGroup: ent-demo-rg-3
SwaName: ent-demo-swa-3
Location: westeurope

jobs:
  swa-create:
    name: Ensure SWA is Created
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create SWA
        id: create-swa
        uses: azure/CLI@v1
        with:
          azcliversion: 2.42.0
          inlineScript: |
            az group create -n $ResourceGroup -l $Location
            az deployment group create --resource-group $ResourceGroup --template-file main.bicep  --parameters name=$SwaName
            az staticwebapp appsettings set --name $SwaName --resource-group $ResourceGroup --setting-name CosmosEndpoint=${{ secrets.COSMOS_ENDPOINT  }} CosmosKey=${{ secrets.COSMOS_KEY }} TodoContainerName=${{ secrets.TODO_CONTAINER_NAME }} TodoDatabaseName=${{ secrets.TODO_DATABASE_NAME }}
